### ISSUE TITLE
How can I display translucent block from texture in this program like glass or leaves?

### ISSUE THREAD

**Issue by Huangtianhao06** [fogleman/Minecraft#103]

**Comment by Huangtianhao06** [comment]
Maybe something to do with texture picture format?

**Comment by Huangtianhao06** [comment]
I'm using texture.png and it's not working...

**Comment by uuk0** [comment]
You must configuration opengl for using alpha values

**Comment by Huangtianhao06** [comment]
Thank you, but can you show me the code to do it?

**Comment by Huangtianhao06** [comment]
Oh I mean the blocks are not showing all the pixels, and it turns out to be black in that part.

**Comment by uuk0** [comment]
I think this should work
glEnable(GL_BLEND)
glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)

(for example past this code in the setup() function)

**Comment by Huangtianhao06** [comment]
I'll try that

**Comment by Huangtianhao06** [comment]
It worked!

**Comment by Huangtianhao06** [comment]
Thank you!

**Comment by Huangtianhao06** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/53070342/64165852-72448000-ce78-11e9-886d-7e1eced01ec4.jpeg)Weird.

**Comment by Huangtianhao06** [comment]
I think I should add something called depth test I guess

**Comment by Huangtianhao06** [comment]
Oh I just didn't disable the hide block surface of these block

**Comment by Huangtianhao06** [comment]
I'll fix that

**Comment by uuk0** [comment]
There may be also another bug that translucent blocks 2 Or More Blocks apart will disable rendering the block behind another

**Comment by Huangtianhao06** [comment]
Yeah, I notice that.

**Comment by uuk0** [comment]
There may be also another bug that translucent blocks 2 Or More Blocks apart will disable rendering the block behind another

**Comment by Huangtianhao06** [comment]
Some blocks displayed after the translucent block will not show behind it

**Comment by Huangtianhao06** [comment]
But that also mean if I display the translucent block after the full blocks, there'll still problems between translucent blocks.

**Comment by uuk0** [comment]
One part (normal behind transparent) can be fixed by using separated batches one for alpha textures and one for non-alpha, for the other I have no clue how to fix it

**Comment by Huangtianhao06** [comment]
ok
