### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by randomusert** [fogleman/Minecraft#153]
gives this error:  GL-FOG is not defined

**Comment by michaelboerman** [comment]
I also received this error. In particular, it fails in [function `setup_fog`](https://github.com/fogleman/Minecraft/blob/65c759c1f43798278e13f6c1a0e038aeeac77656/main.py#L855-L861).

**Comment by michaelboerman** [comment]
Solution is provided in #147; please close this issue.
