### ISSUE TITLE
Line 150 xrange error

### ISSUE THREAD

**Issue by thedobbles** [fogleman/Minecraft#67]
Whenever I run main.py, I get an error at line 150
   NameError: name 'xrange' is not defined

**Comment by kirbyfan64** [comment]
Try running it under Python 2.

**Comment by thedobbles** [comment]
How might i do that?

**Comment by kirbyfan64** [comment]
What OS are you on?(

**Comment by thedobbles** [comment]
Windows 10 x64

**Comment by ProgVal** [comment]
Or you can just apply this patch: https://github.com/fogleman/Minecraft/pull/34/files

**Comment by thedobbles** [comment]
Oh, cool, thanks!
