### ISSUE TITLE
Error in getdisplay method.

### ISSUE THREAD

**Issue by Patil-Sagar** [fogleman/Minecraft#68]
Getting this error:
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

**Comment by fogleman** [comment]
This is an issue with Pyglet, not the Minecraft code.

Are you using a Raspberry Pi?

https://www.raspberrypi.org/forums/viewtopic.php?t=126421&p=846548

**Comment by ProgVal** [comment]
It means you don't have a X server running / the script cannot set it.

**Comment by Patil-Sagar** [comment]
No I am using normal ubuntu 14.0 VM
How can I solve this problem ?
Suggestions are welcomed.

**Comment by ProgVal** [comment]
How do you run this script?

**Comment by Patil-Sagar** [comment]
python main.py

**Comment by Patil-Sagar** [comment]
As per the commands specified

**Comment by ProgVal** [comment]
In a X terminal? A tty?

**Comment by ProgVal** [comment]
Or through ssh?

**Comment by Patil-Sagar** [comment]
on a ubuntu  Vm using putty

**Comment by ProgVal** [comment]
So you connect to the VM using Putty?

Try this:
http://zr6aic.blogspot.fr/2013/09/how-to-setup-putty-to-do-x-forwarding.html

**Comment by ProgVal** [comment]
But I suggest you run the game directly in the VM instead of running it
through SSH, you will get way better performances. (Putty is a SSH client)
