### ISSUE TITLE
Umm IDK how do i fix

### ISSUE THREAD

**Issue by TheButterKing** [fogleman/Minecraft#70]
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 3/14/16 6:54 PM
Description: Rendering entity in world

java.lang.ClassCastException: net.minecraft.client.model.ModelBiped cannot be cast to noppes.mpm.client.model.ModelMPM
	at noppes.mpm.client.RenderMPM.setEntity(RenderMPM.java:420)
	at noppes.mpm.client.RenderEvent.pre(RenderEvent.java:78)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_240_RenderEvent_pre_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:131)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:91)
	at net.aetherteam.aether.client.gui.inventory.GuiContainerAccessories.func_73863_a(GuiContainerAccessories.java:89)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at noppes.mpm.client.EntityRendererAlt.func_78480_b(EntityRendererAlt.java:34)
	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at noppes.mpm.client.RenderMPM.setEntity(RenderMPM.java:420)
	at noppes.mpm.client.RenderEvent.pre(RenderEvent.java:78)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_240_RenderEvent_pre_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:131)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)

-- Entity being rendered --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP)
	Entity ID: 159
	Entity Name: TheButterKing354
	Entity's Exact location: -87.33, 65.62, 294.45
	Entity's Block location: World: (-88,65,294), Chunk: (at 8,4,6 in -6,18; contains blocks -96,0,288 to -81,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00

-- Renderer details --
Details:
	Assigned renderer: stevekung.mods.moreplanets.core.todo.RenderPlayerMP@2cb2c09
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:91)
	at net.aetherteam.aether.client.gui.inventory.GuiContainerAccessories.func_73863_a(GuiContainerAccessories.java:89)

-- Screen render details --
Details:
	Screen name: net.aetherteam.aether.client.gui.inventory.GuiContainerAccessories
	Mouse location: Scaled: (360, 19). Absolute: (720, 662)
	Screen size: Scaled: (683, 351). Absolute: (1366, 702). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['TheButterKing354'/159, l='MpServer', x=-87.33, y=65.62, z=294.45]]
	Chunk stats: MultiplayerChunkCache: 438, 438
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (125,4,105), Chunk: (at 13,0,9 in 7,6; contains blocks 112,0,96 to 127,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 24061 game time, 24061 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 26 total; [EntityHuman['Alisa the Shepherd'/88709, l='MpServer', x=-112.16, y=65.00, z=290.38], EntityHuman['Diego the Farmer'/88711, l='MpServer', x=-119.63, y=64.00, z=291.94], EntityHuman['Mara the Shepherd'/88712, l='MpServer', x=-110.44, y=65.00, z=300.31], EntityHuman['Britt the Baker'/88971, l='MpServer', x=-135.75, y=64.00, z=295.69], EntityHuman['Jaiden the Fisherman'/88714, l='MpServer', x=-118.41, y=65.00, z=300.25], EntityHuman['Ted the Guard'/90125, l='MpServer', x=-110.50, y=65.00, z=302.75], EntityGoron['Goron'/88972, l='MpServer', x=-150.50, y=65.00, z=303.00], EntityHuman['Wilson the Guard'/90127, l='MpServer', x=-137.25, y=65.00, z=312.28], EntityHuman['Zac the Guard'/90126, l='MpServer', x=-122.33, y=64.00, z=286.70], EntityHuman['Lily the Shepherd'/88723, l='MpServer', x=-115.22, y=64.00, z=294.50], EntityHuman['Yvette the Shepherd'/88725, l='MpServer', x=-124.25, y=64.00, z=283.59], EntityHuman['Talitha the Shepherd'/88727, l='MpServer', x=-119.28, y=64.00, z=284.50], EntityHuman['Aaron the Miner'/88734, l='MpServer', x=-126.63, y=65.00, z=314.72], EntityHuman['Drew the Fisherman'/88738, l='MpServer', x=-125.34, y=64.00, z=308.00], EntityHuman['Carly the Farmer'/88740, l='MpServer', x=-127.34, y=65.00, z=310.84], EntityHuman['Abrielle the Baker'/88742, l='MpServer', x=-124.63, y=65.00, z=298.09], EntityHuman['Teri the Shepherd'/88744, l='MpServer', x=-124.50, y=65.00, z=296.94], EntityHuman['Brisa the Shepherd'/88746, l='MpServer', x=-128.50, y=64.00, z=295.03], EntityHuman['Emmy the Guard'/88755, l='MpServer', x=-113.50, y=65.00, z=288.72], EntityHuman['Troy the Guard'/88754, l='MpServer', x=-123.13, y=65.00, z=303.50], EntityHuman['Ira the Toolsmith'/88759, l='MpServer', x=-124.34, y=64.00, z=307.30], EntityHuman['Dixie the Shepherd'/88761, l='MpServer', x=-128.72, y=65.00, z=293.06], EntityHuman['Toby the Fisherman'/88764, l='MpServer', x=-139.09, y=66.00, z=307.54], GCEntityClientPlayerMP['TheButterKing354'/159, l='MpServer', x=-87.33, y=65.62, z=294.45], EntityHuman['Paolo the Guard'/90591, l='MpServer', x=-125.00, y=64.00, z=285.00], EntityTrail['unknown'/502, l='MpServer', x=-87.33, y=65.62, z=294.45]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2865488056 bytes (2732 MB) / 5086642176 bytes (4851 MB) up to 5086642176 bytes (4851 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5000M -Xms5000M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	MorePlanetsASM{} [More Planets Core] (minecraft.jar) 
	UCHIJAAAA	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (1.7.10 orespawn) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.2 (1).jar) 
	UCHIJAAAA	zeldaswordskills{1.7.10-2.3.1} [Zelda Sword Skills] (1.7.10-zeldaswordskills-2.3.1.jar) 
	UCHIJAAAA	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212 Core-V0.2 - 1.7.10.jar) 
	UCHIJAAAA	superslopes{V0.1 - 1.7.10} [Super Slopes] (_Super-Slopes-Mod-1.7.10.jar) 
	UCHIJAAAA	lightsabers{0.7.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-0.7.2.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHIJAAAA	aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
	UCHIJAAAA	MovingWorld{1.7.10-1.8} [Moving World] (movingworld-1.7.10-1.8 (2).jar) 
	UCHIJAAAA	ArchimedesShipsPlus{1.7.10-1.8} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.8 (2).jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAA	CosmeticArmor{1.0.5} [Cosmetic Armor] (CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.2.1_1.7.10 (1).jar) 
	UCHIJAAAA	props{2.2.1} [Decocraft] (Decocraft-2.2.1_1.7.10 (1).jar) 
	UCHIJAAAA	DragonMounts{r39} [Dragon Mounts] (Dragon-Mounts-Mod-1.7.10 (1).jar) 
	UCHIJAAAA	fairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.406.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.406.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2 (1).jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta (1).jar) 
	UCHIJAAAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7 (1).jar) 
	UCHIJAAAA	LittleBlocks{2.2.4.4} [Little Blocks] (LittleBlocks-2.2.4.4 (1).jar) 
	UCHIJAAAA	RadixCore{2.1.1} [RadixCore] (RadixCore-1.7.10-2.1.1-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.1.1.1} [Minecraft Comes Alive] (MCA-1.7.10-5.1.1.1-universal.jar) 
	UCHIJAAAA	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCHIJAAAA	powersuits{0.11.0.294} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.294.jar) 
	UCHIJAAAA	MorePlanet{1.3.0} [More Planets] (More-Planets-1.7.10-1.3.0-Pre-6.jar) 
	UCHIJAAAA	moreplayermodels{1.7.10} [MorePlayerModels] (MorePlayerModels_1.7.10.jar) 
	UCHIJAAAA	openmodularturrets{2.1.8-199} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.1.8-199.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6 (1).jar) 
	UCHIJAAAA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJAAAA	corerm{1.0c} [RikMuld's Core] (RikMuldsCore_1.0c (1).jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) 
	UCHIJAAAA	SC0_SpaceCore{0.7.8} [SpaceCore] (SpaceCore-1.7.10.jar) 
	UCHIJAAAA	universalcoins{1.7.10-1.5.4} [Universal Coins] (Universal-Coins-Mod-1.7.10.jar) 
	UCHIJAAAA	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3 (1).jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4331, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by kirbyfan64** [comment]
This is the wrong issue tracker! From reading the crash dump, this seems to be an issue with Minecraft and the More Player Models mod. You can try posting the log [to the forum](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291730-more-player-models-2-adds-a-character-creation).
