### ISSUE TITLE
Link to traverseda/PyCraft

### ISSUE THREAD

**Issue by traverseda** [fogleman/Minecraft#71]
https://github.com/traverseda/PyCraft

A lot of people are interested in your project, and there are a lot of forks.

I've cloned your repo, with the intent of being a lot more accepting of pull requests. We've already got the start of an object-oriented block system and a perlin noise based terrain generator.

There's a lot of interesting stuff people could do with this project, but most of them would hurt the intent. Would make it less useful as a teaching tool, and obviously would push the line count waay higher.

I don't mind submitting a pull request, but I wanted to make sure you're amenable to this kind of thing before doing it.

**Comment by ProgVal** [comment]
The author answered a similar question: https://github.com/fogleman/Minecraft/pull/66#issuecomment-168450342

**Comment by traverseda** [comment]
Thanks, I appreciate it, and am definitely going to look through that code and see if it supersedes the OO blocks that I've been working on.

This is more about policy though. I'd like it, if instead of saying "it's better for it to remain separate" the answer was "that looks like the kind of pull request PyCraft is looking for".

That way we can consolidate some cool features like that.

**Comment by traverseda** [comment]
I've gotten a bunch of pull requests, it really looks like it's starting to take shape. Just give the word and I'll submit a PR directing people towards traverseda/pycraft it they want to improve the engine.

Probably a blurb like


>This repository is meant for education, and accepts pull requests that help it do that.

>If you want to contribute to something more permissive, check out [pycraft](http://github.com/traverseda/pycraft)



@fogleman
