### ISSUE TITLE
Server Support

### ISSUE THREAD

**Issue by Bayside308** [fogleman/Minecraft#88]
Hello!

I was wondering if you'd consider porting the `server.py` file from your Craft repo to support this. I think it would be useful for learning how networking works with python, and it could be cool to play this with friends, given how it can easily be modified.

Connecting to servers could be done via command line arguments (`py main.py -S <IP>`).

Thanks!

EDIT: For reference: https://github.com/fogleman/Craft/blob/master/server.py

**Comment by Bayside308** [comment]
Bump @fogleman

**Comment by fogleman** [comment]
Feel free to try it yourself - but I'm not really interested in pursuing this myself right now.
